1.3 Update

diff --git a/connect2ssh b/connect2ssh
--- a/connect2ssh
+++ b/connect2ssh
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 : <<HEADER
-SSH-FS BASH CONNECTOR v1.2 on 10 January 2017
+SSH(FS) BASH CONNECTOR v1.3 on 5 October 2017
 Copyright (c) 2017 by Jeremy O'Connell - Cyberweb Solutions, LLC @ www.cyberws.com
 
 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
@@ -20,10 +20,10 @@ HEADER
 ######################################################################
 
 # Version number
-VERSION="1.2"
+VERSION="1.3"
 
-# Title variabe
-TITLE="SSH-FS BASH CONNECTOR"
+# Title variable
+TITLE="SSH(FS) BASH CONNECTOR"
 
 # sqlite3 command
 SQLITE_CMD="sqlite3"
@@ -47,6 +47,7 @@ ACTION_SHORTCUTS[la]="list-accounts"
 ACTION_SHORTCUTS[co]="connect"
 ACTION_SHORTCUTS[dc]="disconnect"
 ACTION_SHORTCUTS[cs]="credits"
+ACTION_SHORTCUTS[vc]="version"
 
 for ACTION_SHORTCUT in "${!ACTION_SHORTCUTS[@]}"
 do
@@ -61,7 +62,7 @@ done
 # Load configuration file and set database
 ####################################################################
 # Get home directory
-HOME_DIR=`echo $HOME`
+HOME_DIR=`echo ~`
 
 # Set SQLITE 
 
@@ -98,9 +99,9 @@ fi
 # Header
 ######################################################################
 
-echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
-echo "$TITLE v$VERSION"
-echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"$'\n'
+#echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
+echo "☀ $TITLE v$VERSION ☀"$'\n'
+#echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"$'\n'
 
 ######################################################################
 # Functions
@@ -109,7 +110,7 @@ echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"$'\n'
 # Footer
 ######################################################################
 DISPLAY_FOOTER() {
-	echo $'\n'$"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
+	echo $'\n'$"-------------------------------------------------------------------"$'\n'$"🖧 Let's connect to something!"$'\n'
 }
 
 # Display install package notices
@@ -138,6 +139,11 @@ COMMAND_CHECK() {
 	command -v sshfs >/dev/null 2>&1 || {
 		DISPLAY_PACKAGE_INSTALL "sshfs" "sshfs" "sshfs"
 	}
+	# Check for curl
+	command -v curl >/dev/null 2>&1 || {
+		DISPLAY_PACKAGE_INSTALL "curl" "curl" "curl"
+	}
+
 
 	# If command_list_status is fail then exit
 	if test "$command_list_status" == "fail"
@@ -177,7 +183,7 @@ ACTION_BANNER() {
 		VERSION_CHECK
 
 		ACTION_BANNER="on"
-		echo "[ACTION] $1"$'\n'
+		echo "ACTION ⯮ $1"$'\n'
 	else
 		INITIALIZE_DB "$1"
 	fi
@@ -192,13 +198,13 @@ ERROR_BANNER() {
 # Display success banner
 ######################################################################
 SUCCESS_BANNER() {
-	echo $'\n'"[~SUCCESS] $1"
+	echo $'\n'$"🗹 SUCCESS: $1"
 }
 
 # Display failed banner
 ######################################################################
 FAILED_BANNER() {
-	echo $'\n'"[~FAILED] $1"
+	echo $'\n'$"🗵 FAILED: $1"
 }
 
 # Menu Header display
@@ -835,6 +841,9 @@ then
 	# Current account number
 	account_count=`$SQLITE_CMD $SQLITE_DB "select count(account_id) from accounts"`
 
+	# Set list compact to n
+	list_compact='n'
+
 	if test "$account_count" == "0"
 	then
 		echo "** No accounts **"
@@ -848,6 +857,12 @@ then
 			list_type="text"
 		fi
 
+		# Compact or Expanded List and no notes
+		if test "$2" != "notes"
+		then
+			read -e -p "Compact List? [y/n]: " -i "y" list_compact
+		fi
+
 		# Set notice for view notes
 		if test "$list_type" == "html"
 		then
@@ -855,10 +870,28 @@ then
 		else
 			text_view=$'\n'$'\n'$"Note: To view account notes rerun command and add space notes"
 		fi
-		echo 
+		echo
 
 		# Get server list
 		mapfile -t SERVER_LIST < <($SQLITE_CMD $SQLITE_DB "select server_id,server_name from servers order by server_name")
+
+		# Set server spacing
+		if test $list_compact == 'y'
+		then
+			if test $list_type == "html"
+			then
+				server_list_returns="<br><br><br>"
+			else
+				server_list_returns=$'\n'$'\n'$'\n'
+			fi
+		else
+			if test $list_type == "html"
+			then
+				server_list_returns="<br><br>"
+			else
+				server_list_returns=$'\n'$'\n'
+			fi
+		fi
 
 		# Load server data
 		for server_details in "${SERVER_LIST[@]}"
@@ -874,9 +907,10 @@ then
 
 			if test "$list_type" == "html"
 			then
-				html_view="$html_view<br><br><br>Server: $server_name [Accounts: $server_account_count]<br>---------------------------------------------------------"
+				html_view="$html_view$server_list_returns"$"Server: $server_name [Accounts: $server_account_count]<br>---------------------------------------------------------<br>"
 			else
-				text_view="$text_view"$'\n'$'\n'$'\n'$"Server: $server_name [Accounts: $server_account_count]"$'\n'$"---------------------------------------------------------"
+				
+				text_view="$text_view$server_list_returns"$"Server: $server_name [Accounts: $server_account_count]"$'\n'$"---------------------------------------------------------"$'\n'
 			fi
 
 			# Get account list
@@ -902,27 +936,47 @@ then
 
 					if test "$list_type" == "html"
 					then
-						html_view="$html_view<br>* $username (ID: $account_id)"
-						# Add notes if requested
-						if test "$2" == "notes"
+						if test "$list_compact" == "y"
 						then
-							html_view="$html_view<br>Notes: $account_notes"
+							html_view="$html_view* $username ($account_id) "
+						else
+							html_view="$html_view* $username (ID: $account_id)"
+							# Add notes if requested
+							if test "$2" == "notes"
+							then
+								html_view="$html_view [Notes] $account_notes"
+							fi
+							html_view="$html_view<br>"
 						fi
 					else
-						text_view="$text_view"$'\n'$"* $username (ID: $account_id)"
-						# Add notes if requested
-						if test "$2" == "notes"
+						if test "$list_compact" == "y"
 						then
-							text_view="$text_view"$'\n'$"Notes: $account_notes"
+							text_view="$text_view* $username ($account_id) "
+						else 
+							text_view="$text_view* $username (ID: $account_id)"
+							# Add notes if requested
+							if test "$2" == "notes"
+							then
+								text_view="$text_view [Notes] $account_notes"
+							fi
+							text_view="$text_view"$'\n'
 						fi
 					fi
 				done
 			else
 				if test "$list_type" == "html"
 				then
-					html_view="$html_view<br>* No accounts"
+					html_view="$html_view* No accounts"
+					if test "$list_compact" == "n"
+					then
+						html_view="$html_view<br>"
+					fi
 				else
-					text_view="$text_view"$'\n'$"* No accounts"
+					text_view="$text_view* No accounts"
+					if test "$list_compact" == "n"
+					then
+						text_view="$text_view"$'\n'
+					fi
 				fi
 			fi		
 		done
@@ -1311,8 +1365,6 @@ then
 	then
 		# Disconnect from server
 		DISCONNECT_SSHFS "$mount_point"
-
-
 	else
 		FAILED_BANNER "Account on given server does not exist!"
 	fi
@@ -1351,6 +1403,35 @@ then
 	fi
 fi
 
+# Version check
+######################################################################
+if test "$action" == "version"
+then
+	ACTION_BANNER "Version Check"
+
+	# Load current version from github
+	GH_VERSION=`curl -s https://raw.githubusercontent.com/cleverwise/connect2ssh/master/version`
+
+	if [ -z $GH_VERSION ]
+	then
+		MSG="🗷 ERROR: UNABLE TO CONNECT TO GITHUB VERSION CHECK!!!"
+		GH_VERSION="Unknown - can NOT connect to GitHub"
+	else
+		if test $GH_VERSION == $VERSION
+		then
+			MSG="🗹 LATEST VERSION!"
+		else
+			MSG="🗷 UPGRADED REQUIRED! VERSIONS DO NOT MATCH!"
+		fi
+	fi
+	echo "$MSG"$'\n'
+	echo "Github Version: $GH_VERSION"
+	echo "Installed Version: $VERSION"
+	echo $'\n'$"Github: https://github.com/cleverwise/connect2ssh"
+fi
+
+
+
 # Credits
 ######################################################################
 if test "$action" == "credits"
@@ -1358,9 +1439,9 @@ then
 	ACTION_BANNER "Credits"
 
 	echo "Lead programmer: Jeremy O'Connell"
-	echo "[] Cyberweb Solutions, LLC @ www.CyberWS.com"$'\n'
+	echo "‣ Cyberweb Solutions, LLC @ www.CyberWS.com"$'\n'
 	echo "Testing and collaboration: Joe Collins"
-	echo "[] EzeeLinux @ www.EzeeLinux.com"
+	echo "‣ EzeeLinux @ www.EzeeLinux.com"
 fi
 
 # List valid actions
@@ -1398,6 +1479,7 @@ then
 
 	MENU_HEADER "Other Actions"
 	MENU_ITEM "credits" "cs" "View programmers/contributors"
+	MENU_ITEM "version" "vc" "Check for current version"
 fi
 
 # List valid actions
